name: Denver Accident Lawyers
favicon: null
layout_spectrum: 0.20430907513946295
typography_spectrum: 0.7184108947403729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7910459130071104
  lightness: 0.4844701113179326
  saturation: 0.1495711246971041
  rhythmicContrast: 0.8199994356837124
purpose: []
